### PR TITLE
Add analytics for dbt.com in addition to getdbt

### PR DESCRIPTION
**Pull request by b-per**
### Description

Allows Snowplow analytics for non US MT

### Checklist

- [x] I have read [the contributing guide](https://github.com/dbt-labs/dbt-core/blob/main/CONTRIBUTING.md) and understand what's expected of me
- [x] I have signed the [CLA](https://docs.getdbt.com/docs/contributor-license-agreements)
- [ ] I have run this code in development and it appears to resolve the stated issue
- [x] I have [opened an issue to add/update docs](https://github.com/dbt-labs/docs.getdbt.com/issues/new/choose), or docs changes are not required/relevant for this PR
- [x] I have run `changie new` to [create a changelog entry](https://github.com/dbt-labs/dbt-core/blob/main/CONTRIBUTING.md#Adding-CHANGELOG-Entry)

### CODE REVIEW

**Review by ericalouie — APPROVED** [review]
big thumbs up 👍

**Comment by b-per** [comment]
@graciegoheen sorry for the ping here, but do you know if it is OK to merge this knowing it's been approved by Ric? And what would be the next steps to get it included in dbt-core

**Comment by graciegoheen** [comment]
Thanks for bumping @b-per - I just added our `ready_for_review` label, which will queue it up for review from our team!

**Review by ChenyuLInx — APPROVED** [review]
This change looks good to me.
I don't have a good way to validate this so will merge once we get confirmation from @b-per

**Pull request merged**
