### PR TITLE
Grouped nodes in lineage graph

### PR DESCRIPTION
**Pull request by mattyb**
Addresses #26, #330

### Description

This PR attempts to address some of the requests for the lineage graph expressed in #26 and #330. Specifically, it adds a dropdown to allow for groupings of nodes based on data and tag attributes. While it doesn't explicitly organize by columns, it can be used with tags to view models in layers (as expressed in [this comment](https://github.com/dbt-labs/dbt-docs/issues/26#issuecomment-546256140) and others below it). It does not rely on hard-coding x coordinates, which was one of the proposals, but I think this is easier to use at the expense of some control.

In order to test the angular module, I also added two packages and jest configuration.

grouping

Would love feedback, and would be happy if anyone has doc files besides the jaffle_shop to play with. Some open questions:
- is this a good idea?
- Are there other groupings that should be added? `package`?
- Should `path` grouping truncate at folder instead of filename?
- Is package an inherent hierarchy or should it be distinct?
- Should clicking on a group node affect the selected pathways?

Additional features that could be in a future issue/PR:
- pass along a default grouping from the project configuration
- Expand/collapse groups (see: https://codesandbox.io/s/vanilla-v9tqe4)

### Checklist

- [x] I have read [the contributing guide](https://github.com/dbt-labs/dbt-core/blob/main/CONTRIBUTING.md) and understand what's expected of me
- [x] I have signed the [CLA](https://docs.getdbt.com/docs/contributor-license-agreements)
- [x] I have run this code in development and it appears to resolve the stated issue
- [ ] I have [opened an issue to add/update docs](https://github.com/dbt-labs/docs.getdbt.com/issues/new/choose), or docs changes are not required/relevant for this PR
- [ ] I have run `changie new` to [create a changelog entry](https://github.com/dbt-labs/dbt-core/blob/main/CONTRIBUTING.md#Adding-CHANGELOG-Entry)

### CODE REVIEW

**Comment by jtcohen6** [comment]
@mattyb This is pretty cool :)

Unfortunately, our team isn't able to prioritize much work on `dbt-docs` these days, so I can't promise that we'll be able to review a contribution this hefty within the next few days or weeks. But it did strike me as serendipitous that you opened this PR around the same time I opened this discussion: https://github.com/dbt-labs/dbt-core/discussions/6730

**Comment by mattyb** [comment]
@jtcohen6 Glad you think it's cool! Appreciate the quick response and expectation setting. 

And serendipitous indeed. It seems like dags just keep growing. I think some of the foundational pieces of this PR may be useful for groups, but that users with merely dozens of models may still find it useful to aggregate by other attributes. If that holds, we'd probably want to find a different term than "grouping" in this ui/code.

**Comment by Luttik** [comment]
This looks amazing! I really wish this could be reviewed and merged.

**Comment by Luttik** [comment]
@mattyb Is there a way to use this with existing DBT projects without having dbt-labs merging this into dbt-core?

**Comment by mattyb** [comment]
Thanks for the feedback @Luttik! The easiest way would probably be to follow [the steps here](https://github.com/dbt-labs/dbt-docs/blob/main/CONTRIBUTING.md#running-dbt-docs-in-development) for running dbt-docs in development mode.

**Pull request closed without merging**
